export const FETCH_USERS_START = 'FETCH_USERS_START'
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS'
export const FETCH_USERS_FAIL = 'FETCH_USERS_FAIL'

export const GET_SOMETHING_START = 'GET_SOMETHING_START'
export const GET_SOMETHING_SUCCESS = 'GET_SOMETHING_SUCCESS'
export const GET_SOMETHING_FAIL = 'GET_SOMETHING_FAIL'
