steps:
  # build the container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/doublee-sample-20210405:${SHORT_SHA}", "."]
    # push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/doublee-sample-20210405"]
    # deploy container image to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "beta",
        "run",
        "deploy",
        "doublee-sample-20210405",
        "--image",
        "gcr.io/$PROJECT_ID/doublee-sample-20210405:${SHORT_SHA}",
        "--add-cloudsql-instances",
        "doublee-sql",
        --set-env-vars,
        "INSTANCE_CONNECTION_NAME=doublee-sample-20210405:europe-west2:doublee-mysql",
        --set-env-vars,
        "DB_USER=sqlserver",
        --set-env-vars,
        "DB_PASS=sogismhI0P2aM6kl",
        --set-env-vars,
        "DB_NAME=sample",
        "--region",
        "europe-west2",
        "--allow-unauthenticated",
        "--platform",
        "managed",
      ]
    env:
      - "PORT=8080"
images:
  - gcr.io/$PROJECT_ID/doublee-sample-20210405
